### ISSUE TITLE
BU_3DFE dataset

### ISSUE THREAD

**Issue by peteryanj** [cating341/RGB-D-Face-Recognition#1]
Dear Dr.cating341:
   I am  interesing in code of RGB-D Face Recognition research ,but  I didn't find BU_3DFE  dataset in your code , I would appreciate it if you provide me the BU-3DFE dataset.
   I am looking forward to hearing from you,thank you very much!
   best,
   sincerely

**Comment by miraclewp** [comment]
Hello, 
I want to get some RGB-D face data sets. Could you provide me some or share some download links? Thank you very much.
all the best.

**Comment by kaiyangtongxue** [comment]
您好，非常抱歉惊扰到了您！实属无奈，学校硬件条件有限无法复原数据集。能给一份数据集吗？

**Comment by cating341** [comment]
Sorry that due to the license, we cannot provide any related data. If you need it, please request the dataset by yourself. [[link]](http://www.cs.binghamton.edu/~lijun/Research/3DFE/3DFE_Analysis.html)

**Comment by kaiyangtongxue** [comment]
Hello, which data set do I need to apply for in the link? Thank you



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cating341"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 下午3:57
收件人: "cating341/RGB-D-Face-Recognition"<RGB-D-Face-Recognition@noreply.github.com&gt;; 
抄送: "杨小坏"<208108346@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [cating341/RGB-D-Face-Recognition] BU_3DFE dataset (#1)




Closed #1.
