### ISSUE TITLE
Hello, I would like to consult about the data set.

### ISSUE THREAD

**Issue by miraclewp** [cating341/RGB-D-Face-Recognition#2]
I'm studying in this field. Can you give me a data set of RGB-D face? Thank you very much.

**Comment by kaiyangtongxue** [comment]
数据集要到了吗

**Comment by cating341** [comment]
Sorry that due to the license, we cannot provide any related data. If you need it, please request the dataset by yourself. [[link]](http://www.cs.binghamton.edu/~lijun/Research/3DFE/3DFE_Analysis.html)
